### ISSUE TITLE
Error in primary documented example?

### ISSUE THREAD

**Issue by vdksoda** [cognitedata/oryx#102]
I am starting out my F# journey and decided to try the Oryx framework as a HTTP client. I faced this issue when I copy-pasted your primary documented example. 
```
Result: Error
  System.Exception: Must set HttpClient
   at Oryx.HttpContextModule.defaultRequest@125.Invoke(Unit unitVar0)
   at Oryx.Fetch.fetch@72-1.MoveNext()
   at Oryx.Pipeline.Core.runUnsafeAsync@35.MoveNext()
   at Oryx.Pipeline.Core.runAsync@42.MoveNext()
```

Here is a screenshot from Visual Studio Preview for Mac showcasing the code with the error.
![image](https://user-images.githubusercontent.com/12879372/159866264-0e4de80d-357c-4e50-9ab1-4b51a4c1aff6.png)

I found by moving `withHttpClient client` above `fetch` solved the problem. Is this an error or am I using the example code wrong?
![image](https://user-images.githubusercontent.com/12879372/159866655-ee7b0b1e-dfb5-4934-b1be-9e6fcd8b9b65.png)

**Comment by dbrattli** [comment]
Thanks for submitting the issue. You are absolutely right, and we will fix this as soon as possible.
