### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by kaashyapan** [cognitedata/oryx#60]
Hello

Thanks for another great project. 

I was reading through this and was curious what the situation is with regards to connection pooling.
https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core

Do you have any recommendations about how it can be handled using this library ?

**Comment by dbrattli** [comment]
Yes, with Oryx you add the `HttpClient` to the context using `withHttpClient`. The client can be any client e.g `HttpClient`, `HttpClient(socketsHandler)`, or produced by `IHttpClientFactory.CreateClient`. The context you make can be reused for every request or you can create a new context for each request so you can effectively have "base" context that reuses a HttpClient that provides connection pooling

Example: https://github.com/cognitedata/oryx/blob/master/examples/Program.fs#L47

**Comment by kaashyapan** [comment]
Thanks much.
