### ISSUE TITLE
Mention instructions to have FSharp.Control.Tasks available

### ISSUE THREAD

**Issue by ryepesg** [cognitedata/oryx#79]
As a new user to the .NET ecosystem, trying to use Oryx was not straightforward since `FSharp.Control.Tasks` was not available in my system (MacOS) after following the instructions: `dotnet add package Oryx`

Next I tried: `nuget install Oryx`

But now I am facing:

_Error: The imported project ".paket/Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "../../.paket/Paket.Restore.targets" is correct, and that the file exists on disk_

Beginner friendly instructions or at least links included in the Getting Started guide would be appreciated, thanks!

**Comment by ryepesg** [comment]
Another suggestion that could be mentioned is: `#r "nuget: Oryx"`

**Comment by dbrattli** [comment]
Oryx (last beta) now uses F# 6 builtin task support so Ply or Tasbuilder is not required anymore
